# Generated by Django 5.1.2 on 2024-10-25 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Ya existe un usuario con este correo."},
                max_length=255,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
    ]
